19-Extract-and-label-data-based-on-user-input
Devtailor/Service-Module pull request #14
Opened 2023-03-15 20:43 UTC by 1AhmedYasser

2023-04-05 22:18 UTC, baha-a requested changes
If you're using VS Code you could configure it to add empty line at the end of each file automatically on save.

2023-04-05 22:18 UTC, baha-a commented on GUI/src/services/entities.ts
> +  console.log(`a7a ${data}`)
Remove the console.log statement.

2023-04-05 22:18 UTC, baha-a commented on DSL/OpenSearch/init.sh
> +curl -L -X POST 'http://localhost:9200/_scripts/get-services-stat' -H 'Content-Type: application/json' -H 'Cookie: customJwtCookie=test' --data-binary "@templates/get-services-stat.json"
Add empty line here.

2023-04-05 22:18 UTC, baha-a commented on DSL/OpenSearch/fieldMappings/intents.json
> +}
Add empty line here.

2023-04-05 22:18 UTC, baha-a commented on DSL/Opensearch/fieldMappings/services.json
> +}
Add empty line here.

2023-04-05 22:18 UTC, baha-a commented on GUI/src/pages/Training/IntentsFollowupTraining/index.tsx
> +          ].map((tab, index) => (
Please refactor this array into a variable for better readability.

2023-04-06 06:10 UTC, trevorling requested changes

2023-04-06 06:10 UTC, trevorling commented on GUI/src/utils/generateUEID.ts
> +export const generateUEID = () => {
I'd prefer to use the `UUID` library instead of a custom solution.

2023-04-06 07:27 UTC, Minwasko requested changes

2023-04-06 07:27 UTC, Minwasko commented on GUI/src/pages/Training/IntentsFollowupTraining/index.tsx
> +      <h1>{t('training.intents.followupTraining')}</h1>
It looks like this translation is missing from the i18n file. Please add all missing entries there.

2023-04-13 06:52 UTC, trevorling commented
@1AhmedYasser 
Please resolve conflicts

2023-04-17 07:07 UTC, trevorling approved these changes
@1AhmedYasser 
Please go over the previous comments- related with `let` and `const`.

2023-04-18 07:08 UTC, Minwasko approved these changes

2023-04-18 07:31 UTC, baha-a approved these changes

2023-04-20 07:05 UTC, trevorling approved these changes

2023-04-27 07:15 UTC, merged