26-Create-Ruuter-based-SiGa-Service-Template
Devtailor/Service-Module pull request #22
Opened 2023-04-04 01:48 UTC by 1AhmedYasser

2023-04-06 06:14 UTC, trevorling requested changes

2023-04-06 06:14 UTC, trevorling commented on DSL/Ruuter/POST/templates/siga.yml
> +  next: end
Please add a new line at the end on file.

2023-04-06 06:14 UTC, trevorling commented on docker-compose-siga.yml
> +
Please remove the an empty line (line 4)

2023-04-06 06:14 UTC, trevorling commented on docker-compose-siga.yml
> +    driver: bridge
Please add an empty line at the end of the file.

2023-04-06 07:10 UTC, Minwasko approved these changes

2023-04-06 08:11 UTC, 1AhmedYasser commented on DSL/Ruuter/POST/templates/siga.yml
> +  next: end
This one was already added

2023-04-06 08:12 UTC, 1AhmedYasser commented on docker-compose-siga.yml
> +    driver: bridge
Added it

2023-04-06 08:20 UTC, trevorling approved these changes

2023-04-13 06:52 UTC, trevorling commented
@1AhmedYasser 
Please resolve conflicts

2023-04-18 07:26 UTC, trevorling approved these changes

2023-04-27 07:14 UTC, merged