21 GUI based service conditions manipulation
Devtailor/Service-Module pull request #23
Opened 2023-04-04 07:19 UTC by baha-a

2023-04-20 04:29 UTC, 1AhmedYasser approved these changes

2023-04-20 07:47 UTC, Minwasko requested changes

2023-04-20 07:47 UTC, Minwasko commented on GUI/src/RootComponent.tsx
> +        <Route path={ROUTES.FLOW_ROUTE} element={<ServiceFlowPage />} />
Please move these 2 routes outside of layout element as they previously were. 
In the design these pages don't have a menu

2023-04-20 07:47 UTC, Minwasko commented on GUI/src/components/APIEndpointCard/index.tsx
> +import "./APIEndpointCard.scss"
Please revert this change back to `import "./ApiEndpointCard.scss";` and rename the directory to `ApiEndpointCard`

2023-04-20 07:47 UTC, Minwasko commented on GUI/src/components/FlowElementsPopup/ConditionInput.tsx
> +        setName("name + ' ' + _item.value")
Is it supposed to be like that? Currently it's just a string

2023-04-20 07:47 UTC, Minwasko commented on GUI/src/components/index.tsx
> +import RequestVariables from "./APIEndpointCard/Endpoints/RequestVariables";
Please revert changes to `ApiEndpointCard` and elements in it's directory. Let's make sure that they are all under `/ApiEndpointCard`

2023-04-20 07:47 UTC, Minwasko commented on GUI/src/components/FlowElementsPopup/index.tsx
> +      {type !== 'input' &&
You can remove this part, it was just for testing and to show that it works.

2023-04-20 07:47 UTC, Minwasko commented on GUI/src/pages/ServiceFlowPage.tsx
> +        addRuleCount={() => setUpdatedRules([null, null, null])}
You can remove addRuleCount logic if it's not needed. It was there just for testing and to show how that it works

2023-04-25 13:33 UTC, Minwasko approved these changes

2023-04-25 13:40 UTC, trevorling approved these changes

2023-04-26 01:11 UTC, merged