87 Create a document to sign
Devtailor/Service-Module pull request #25
Opened 2023-04-18 10:33 UTC by baha-a

2023-04-20 08:25 UTC, Minwasko requested changes

2023-04-20 08:25 UTC, Minwasko commented on GUI/src/RootComponent.tsx
> +        <Route path={ROUTES.FLOW_ROUTE} element={<ServiceFlowPage />} />
Please move `NewServicePage` and `ServiceFlowPage`routes outside of `Layout` back to where they previously were, as in the design they do not have a menu

2023-04-20 08:25 UTC, Minwasko commented on GUI/src/components/APIEndpointCard/index.tsx
> +import "./APIEndpointCard.scss";
Please revert this change back to `import "./ApiEndpointCard.scss";` and rename the directory to `/ApiEndpointCard`

2023-04-20 08:25 UTC, Minwasko commented on GUI/src/components/Endpoints/Custom/index.tsx
> +import React from "react";
This file must've been carried over from my branch when I was developing, please remove this file, since the up to date version is now under `components/ApiEndpointCard/..`

2023-04-20 08:25 UTC, Minwasko commented on GUI/src/components/index.tsx
> +import EndpointResqlComponent from "./APIEndpointCard/Endpoints/ResqlComponent";
Please revert changes to `ApiEndpointCard` and elements in it's directory. Let's make sure that they are all under `/ApiEndpointCard` as they were previously

2023-04-20 08:25 UTC, Minwasko commented on GUI/src/pages/ServiceFlowPage.tsx
> +      {visiblePopupNode && (
In https://github.com/Devtailor/Service-Module/pull/23 Bahaa moved this popup content to a separate component. So let's first merge that PR and then you can update this PR so we would have everything up to date, otherwise these changes will be lost when merging

2023-04-27 06:15 UTC, 1AhmedYasser approved these changes

2023-04-27 06:54 UTC, trevorling commented on GUI/src/components/APIEndpointCard/index.tsx
Rename: APIEndpointCard -> ApiEndpointCard

2023-04-27 08:03 UTC, trevorling approved these changes

2023-04-27 09:14 UTC, merged