38 rest service services to fetch a list of all services
Devtailor/Service-Module pull request #3
Opened 2023-03-01 10:23 UTC by baha-a

2023-03-01 19:07 UTC, 1AhmedYasser commented on DSL/Ruuter/GET/services.yml
> +    url: http://custom_node_server:3003/ruuter/list
I think we can enhance the name a little bit to be `node_server` or `services_node_server`

2023-03-01 19:08 UTC, 1AhmedYasser requested changes
Small Changes Required

2023-03-02 07:17 UTC, baha-a commented on DSL/Ruuter/GET/services.yml
> +    url: http://custom_node_server:3003/ruuter/list
Renamed.

2023-03-02 08:00 UTC, 1AhmedYasser approved these changes

2023-03-02 13:29 UTC, trevorling approved these changes

2023-03-03 07:32 UTC, merged