91 Service flow test results based on Ruuter logs
Devtailor/Service-Module pull request #31
Opened 2023-04-28 06:34 UTC by baha-a

2023-04-28 06:50 UTC, Minwasko approved these changes

2023-04-28 08:11 UTC, trevorling requested changes

2023-04-28 08:11 UTC, trevorling commented on DSL/Liquibase/changelog/1682662304-ruuter-requests-logs.sql
> +CREATE TABLE requestLogs (
Please rename: `request_logs`

2023-04-28 08:12 UTC, trevorling commented on DSL/Ruuter/POST/generate-document.yml
> +fromatUserInput:
Typo: `fromat` -> `format`

2023-04-28 08:18 UTC, trevorling commented on DSL/Ruuter/POST/generate-document.yml
> +  next: returnSuccess
Http.get and body has data?!

2023-05-02 06:14 UTC, trevorling approved these changes

2023-05-02 07:29 UTC, 1AhmedYasser approved these changes

2023-05-04 09:13 UTC, trevorling commented on DSL/Liquibase/changelog/1682662304-ruuter-requests-logs.sql
> +  content TIMESTAMPTZ NOT NULL DEFAULT NOW(),
`,` comma is redundant here!

2023-05-04 09:14 UTC, trevorling commented
@baha-a 
One minor fix what came out!

2023-05-05 06:32 UTC, merged