18 Create conversation scripts to get user input
Devtailor/Service-Module pull request #32
Opened 2023-04-28 06:39 UTC by baha-a

2023-05-05 07:28 UTC, trevorling requested changes

2023-05-05 07:28 UTC, trevorling commented on GUI/src/pages/SerivceSettingPage.tsx
Type in file name

2023-05-05 07:28 UTC, trevorling commented on GUI/src/pages/SerivceSettingPage.tsx
> +const SerivceSettingPage: React.FC = () => {
Please fix the typo.

2023-05-05 07:28 UTC, trevorling commented on docker-compose.yml
> +      - application.cors.allowedOrigins=http://localhost:3006
Why did you change it?

2023-05-05 07:30 UTC, trevorling commented on GUI/src/types/step.ts
> +export enum StepType {
Redundant- duplicate.
It's in a separate file - `step-type.enum.ts`

Please remove it from here.

2023-05-08 02:39 UTC, 1AhmedYasser approved these changes

2023-05-08 02:39 UTC, 1AhmedYasser commented
Please Resolve Conflicts

2023-05-08 11:06 UTC, baha-a commented on docker-compose.yml
> +      - application.cors.allowedOrigins=http://localhost:3006
I did not changed it. I just need to merge main with this branch.

2023-05-09 06:47 UTC, trevorling approved these changes

2023-05-09 07:00 UTC, Minwasko requested changes

2023-05-09 07:00 UTC, Minwasko commented on DSL/Ruuter/GET/domain-file.yml
> +  wrapper: false
Please revert this change, or make sure that other endpoints using it will work with `wrapper: false`

2023-05-09 07:20 UTC, baha-a commented on DSL/Ruuter/GET/domain-file.yml
> +  wrapper: false
Reverted.

2023-05-09 07:31 UTC, Minwasko approved these changes

2023-05-10 08:24 UTC, merged