41 Changing the status of a Service (active / inactive / draft)
Devtailor/Service-Module pull request #36
Opened 2023-05-09 06:13 UTC by trevorling

2023-05-09 07:49 UTC, Minwasko approved these changes

2023-05-09 09:23 UTC, baha-a requested changes

2023-05-09 09:23 UTC, baha-a commented on GUI/src/pages/OverviewPage.tsx
> +    fetchServices();
Why not just calling `loadServicesList()` immediately?

```
useEffect(() => {
    loadServicesList();
}, []);
```

2023-05-09 09:23 UTC, baha-a commented on GUI/src/pages/OverviewPage.tsx
> +        usedCount: 0,
Is this correct, should't be `usedCount: item.usedCount`?
If it's correct, please reorder the properties by moving `usedCount: 0` to the bottom to make it more obvious.

2023-05-10 07:18 UTC, 1AhmedYasser approved these changes

2023-05-10 08:16 UTC, Minwasko commented on GUI/src/pages/OverviewPage.tsx
> +        usedCount: 0,
Currently this usedCount data is mocked, so we can't use it with actual services, thus it is 0 for now

2023-05-10 08:27 UTC, merged