16 Test Service Flow improvements
Devtailor/Service-Module pull request #39
Opened 2023-05-09 19:24 UTC by trevorling

2023-05-10 07:23 UTC, baha-a requested changes

2023-05-10 07:23 UTC, baha-a commented on GUI/src/pages/ServiceFlowPage.tsx
> +          console.log(updatedNode);
Please remove `console.log(updatedNode);` from here.

2023-05-10 11:01 UTC, baha-a approved these changes

2023-05-11 14:24 UTC, 1AhmedYasser approved these changes

2023-05-11 14:27 UTC, merged