9-Automatically-generating-REST-endpoint's-key-fields
Devtailor/Service-Module pull request #6
Opened 2023-03-05 22:33 UTC by 1AhmedYasser

2023-03-14 06:54 UTC, trevorling requested changes

2023-03-14 06:54 UTC, trevorling commented on GUI/src/components/MainNavigation/index.tsx
Let's use single quotes. 
It's hard to do the review if there are a lot of changes that are related to the double quotes change.

2023-03-14 06:54 UTC, trevorling commented on GUI/src/constants/menuIcons.tsx
Let's use single quotes.
It's hard to do the review if there are a lot of changes that are related to the double quotes change.

2023-03-14 06:54 UTC, trevorling commented on GUI/src/pages/NewServicePage.tsx
> +    if (jsonSchema != undefined) {
Isn't this enough?
```Ts
if (jsonSchema) {....}

2023-03-14 06:54 UTC, trevorling commented on GUI/src/pages/OverviewPage.tsx
Please revert back to single quotes.

2023-03-14 06:54 UTC, trevorling commented on GUI/src/types/endpointType.ts
We have `routes-constants.ts` and here the file name is `endpointType.ts` - which naming convention we are using?

2023-03-15 07:26 UTC, baha-a approved these changes

2023-03-15 07:26 UTC, baha-a commented on GUI/src/resources/api-constants.ts
Please add newline at end of file.

2023-03-15 07:26 UTC, baha-a commented on DSL/Ruuter/POST/services/open-api-spec.yml
Please add newline at end of file.

2023-03-15 07:34 UTC, trevorling approved these changes

2023-03-22 08:38 UTC, merged