36 Sticky Ruuter DSL to provide user input
Devtailor/Service-Module pull request #7
Opened 2023-03-05 23:59 UTC by baha-a

2023-03-06 11:10 UTC, 1AhmedYasser approved these changes

2023-03-07 06:51 UTC, trevorling requested changes

2023-03-07 06:51 UTC, trevorling commented on DSL/Node/src/ruuter.ts
> +    return res.status(500).send({ message: 'Cann\'t read the file' })
Typo: `Cann\'t` -> `Can\'t`

2023-03-07 07:52 UTC, trevorling approved these changes

2023-03-07 07:52 UTC, baha-a commented on DSL/Node/src/ruuter.ts
> +    return res.status(500).send({ message: 'Cann\'t read the file' })
Fixed.

2023-03-08 08:17 UTC, merged