41-42-service-status
Devtailor/Service-Module pull request #8
Opened 2023-03-08 01:15 UTC by 1AhmedYasser

- Added set/get Status SQL's
- Added set/get Status Ruuter DSL's

2023-03-09 07:53 UTC, trevorling requested changes

2023-03-09 07:53 UTC, trevorling commented on DSL/Liquibase/changelog/1678307467-add-ruuter-types.sql
> +ADD COLUMN ruuter_type TEXT DEFAULT 'GET';
Are you sure that you want to allow `text` as a type?
I'd like to use an enum here.
Then you are able to use only the values which are defined in the enum. 
Now you are able to set the `ruuter_type` to `cat` for example.

2023-03-09 07:53 UTC, trevorling commented on DSL/Resql/services/get-service.sql
> +WHERE id = :id;
I'd rename the file:
`get-service-name-by-id.sql`
What do you think?

2023-03-09 07:53 UTC, trevorling commented on DSL/Ruuter/POST/services/status.yml
> +in_activate_service:
`in_activate_service` -> `deactivate_service`
In my opinion, it's more descriptive.

2023-03-09 07:53 UTC, trevorling commented on README.md
> +- When creating new migrations, use the helper `./create-migration.sh name-of-migration` which will create a timestamped file in the correct directory and add the required headers
Thanks for the update! :)

2023-03-09 07:57 UTC, 1AhmedYasser commented on README.md
> +- When creating new migrations, use the helper `./create-migration.sh name-of-migration` which will create a timestamped file in the correct directory and add the required headers
Your Mostly Welcome 👍

2023-03-09 18:28 UTC, baha-a approved these changes

2023-03-10 10:13 UTC, trevorling commented on DSL/Liquibase/changelog/1678307467-add-ruuter-types.sql
> +ADD COLUMN ruuter_type TEXT DEFAULT 'GET';
```sql
CREATE TYPE ruuter_request_type AS ENUM ('GET', 'POST');

ALTER TABLE services 
ADD COLUMN ruuter_type ruuter_request_type DEFAULT 'GET';

2023-03-10 10:13 UTC, trevorling commented on DSL/Resql/services/add.sql
> +VALUES (:name, :description,:type);
```sql
INSERT INTO services (name, description,ruuter_type)
VALUES (:name, :description,:ruuter_type::ruuter_request_type);

2023-03-10 10:13 UTC, trevorling commented on DSL/Ruuter/POST/services/add.yml
> +      type: ${type}
`type` -> `ruuter_type`
```
ruuter_type: ${type}

2023-03-10 10:15 UTC, trevorling commented on DSL/Ruuter/POST/services/add.yml
> +    type: ${incoming.body.type}
If possible then please do:  `.toUpperCase()`

2023-03-10 11:08 UTC, trevorling commented on DSL/Ruuter/POST/services/add.yml
> +    - condition: ${type === 'GET'}
```
${type === 'GET' || type === 'get'}

2023-03-13 06:31 UTC, trevorling requested changes

2023-03-13 06:31 UTC, trevorling commented on DSL/Ruuter/POST/services/add.yml
> +      ruuter_type: ${type.toUpperCase()}
Please use this `.toUpperCase()` in line 5.
Then you don't need to do it in multiple places.

2023-03-13 09:50 UTC, trevorling approved these changes

2023-03-13 09:54 UTC, merged